-- AlterTable
ALTER TABLE `Device` ADD COLUMN `lastSeenAt` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('ONLINE', 'OFFLINE') NOT NULL DEFAULT 'OFFLINE';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `role` ENUM('ADMIN', 'EMPLOYEE') NOT NULL DEFAULT 'EMPLOYEE';
